#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${API_DIR}"

EXPERIMENTAL_DATA_DIR="${API_EXPERIMENTAL_DATA_DIR:-.control-plane/experimental}"
EXPERIMENTAL_TMP_DIR="${DATA_TMP_DIR_EXPERIMENTAL:-${EXPERIMENTAL_DATA_DIR}/tmp}"

mkdir -p "${EXPERIMENTAL_DATA_DIR}" "${EXPERIMENTAL_TMP_DIR}"

cp -f "./providers.json" "${EXPERIMENTAL_DATA_DIR}/providers.json" 2>/dev/null || true
cp -f "./keys.json" "${EXPERIMENTAL_DATA_DIR}/keys.json" 2>/dev/null || true
cp -f "./models.json" "${EXPERIMENTAL_DATA_DIR}/models.json" 2>/dev/null || true

NODE_ENV_VALUE="${NODE_ENV:-experimental}"
API_DIST_DIR_VALUE="${API_DIST_DIR:-dist/experimental}"
PORT_VALUE="${PORT:-3310}"
CLUSTER_WORKERS_VALUE="${CLUSTER_WORKERS:-1}"
PORT_RETRY_COUNT_VALUE="${PORT_RETRY_COUNT:-0}"
DATA_SOURCE_PREFERENCE_VALUE="${DATA_SOURCE_PREFERENCE:-redis}"
EXPERIMENTAL_SOURCE_REDIS_DB_VALUE="${EXPERIMENTAL_SOURCE_REDIS_DB:-${CONTROL_PLANE_SOURCE_REDIS_DB:-0}}"
EXPERIMENTAL_TARGET_REDIS_DB_VALUE="${REDIS_DB_EXPERIMENTAL:-${EXPERIMENTAL_TARGET_REDIS_DB:-${CONTROL_PLANE_TARGET_REDIS_DB:-1}}}"
API_PROVIDERS_FILE_VALUE="${API_PROVIDERS_FILE_EXPERIMENTAL:-${EXPERIMENTAL_DATA_DIR}/providers.json}"
API_KEYS_FILE_VALUE="${API_KEYS_FILE_EXPERIMENTAL:-${EXPERIMENTAL_DATA_DIR}/keys.json}"
API_MODELS_FILE_VALUE="${API_MODELS_FILE_EXPERIMENTAL:-${EXPERIMENTAL_DATA_DIR}/models.json}"
DATA_TMP_DIR_VALUE="${DATA_TMP_DIR_EXPERIMENTAL:-${EXPERIMENTAL_TMP_DIR}}"

env \
  NODE_ENV="${NODE_ENV_VALUE}" \
  API_DIST_DIR="${API_DIST_DIR_VALUE}" \
  PORT="${PORT_VALUE}" \
  CLUSTER_WORKERS="${CLUSTER_WORKERS_VALUE}" \
  PORT_RETRY_COUNT="${PORT_RETRY_COUNT_VALUE}" \
  DATA_SOURCE_PREFERENCE="${DATA_SOURCE_PREFERENCE_VALUE}" \
  EXPERIMENTAL_SOURCE_REDIS_DB="${EXPERIMENTAL_SOURCE_REDIS_DB_VALUE}" \
  REDIS_DB_EXPERIMENTAL="${EXPERIMENTAL_TARGET_REDIS_DB_VALUE}" \
  API_PROVIDERS_FILE_EXPERIMENTAL="${API_PROVIDERS_FILE_VALUE}" \
  API_KEYS_FILE_EXPERIMENTAL="${API_KEYS_FILE_VALUE}" \
  API_MODELS_FILE_EXPERIMENTAL="${API_MODELS_FILE_VALUE}" \
  DATA_TMP_DIR_EXPERIMENTAL="${DATA_TMP_DIR_VALUE}" \
  bash ../../bun.sh run ./dev/cloneRedisDb.bun.ts

exec env \
  NODE_ENV="${NODE_ENV_VALUE}" \
  API_DIST_DIR="${API_DIST_DIR_VALUE}" \
  PORT="${PORT_VALUE}" \
  CLUSTER_WORKERS="${CLUSTER_WORKERS_VALUE}" \
  PORT_RETRY_COUNT="${PORT_RETRY_COUNT_VALUE}" \
  DATA_SOURCE_PREFERENCE="${DATA_SOURCE_PREFERENCE_VALUE}" \
  REDIS_DB="${EXPERIMENTAL_TARGET_REDIS_DB_VALUE}" \
  API_PROVIDERS_FILE="${API_PROVIDERS_FILE_VALUE}" \
  API_KEYS_FILE="${API_KEYS_FILE_VALUE}" \
  API_MODELS_FILE="${API_MODELS_FILE_VALUE}" \
  DATA_TMP_DIR="${DATA_TMP_DIR_VALUE}" \
  bash ../../bun.sh run ./server.launcher.bun.ts
